// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.Beep();
Console.WriteLine("Benvenuto");
Console.WriteLine("Gennaio");
Console.WriteLine("Febbraio");
Console.WriteLine("Marzo");
Console.WriteLine("Aprile");
Console.WriteLine("Maggio");
Console.WriteLine("Giugno");
Console.WriteLine("Luglio");
Console.WriteLine("Agosto");
Console.WriteLine("Settembre");
Console.WriteLine("Ottobre");
Console.WriteLine("Novembre");
Console.WriteLine("Dicembre");
Console.Beep();
Console.WriteLine("Inserisci il tuo mese preferito");
var mese = Console.ReadLine();
Console.WriteLine("Grazie di aver scritto " + mese);
Console.Beep();
